version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/myapp
      - JWT_SECRET=your_jwt_secret
      - ENCRYPTION_KEY=your_encryption_key
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - '8090:80'
    depends_on:
      - backend

  mongo:
    image: mongo:4.4.6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
